baseURL = "https://example.com/"
title = "Degen"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

#[services]
#[services.disqus]
#disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "degenware"
  info = "A guy learning cybersecurity"
  #description = "John Doe's personal website"
  keywords = "blog,cybersecurity,personal"
  avatarurl = "images/avatar.png"
  #gravatar = "john.doe@example.com"

 # faviconSVG = "/img/favicon.svg"
  favicon_32 = "images/favicon-32x32.ico"
  favicon_16 = "images/favicon-16x16.ico"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
#[[params.social]]
#  name = "Github"
#  icon = "fa-brands fa-github fa-2x"
#  weight = 1
#  url = "https://github.com/degenware"
[[params.social]]
  name = "X"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://x.com/degenware"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 7
  url  = "posts/"
#[[menu.main]]
#  name = "About"
#  weight = 2
#  url = "about/"
